Repository agrc/api-client, pull requests merged in 2021-11, with the labels that each got.

#73 fix: correct object shape for dispatcher
  src/components/FieldLinker.jsx
Labels: bug

#77 fix: make street field label more clear
  src/components/FieldLinker.jsx
Labels: bug

#80 Add link to our status page
  src/main.js
  src/pages/Error.jsx
Labels: enhancement

#81 Upgrade electron and other dependencies
  package-lock.json
  package.json
Labels: chore

#82 Add fail fast - A fast failure occurs when the first records do not succeed to geocode.
  src/pages/Geocoding.jsx
  src/services/geocode.js
Labels: enhancement

#86 Update electron and other dependencies
  package-lock.json
  package.json
  src/services/csv.js
  src/services/errors.js
  src/services/geocode.js
Labels: chore

#91 Add email confirmation docs to api key page
  src/pages/ApiKey.jsx
Labels: enhancement

#92 Remember window position between sessions
  package-lock.json
  package.json
  src/main.js
Labels: enhancement

#95 Fix hung geocoding
  src/services/geocode.js
Labels: bug

#94 Update electron and other dependencies
  package-lock.json
  package.json
Labels: chore
