Repository agrc/api-client, pull requests merged in 2022-04, with the labels that each got.

#131 Update dependencies
  package-lock.json
  package.json
  src/main.jsx
Labels: chore

#133 Add mock server for testing the API
  package-lock.json
  package.json
  src/services/geocode.js
  tests/mocks/server.js
Labels: testing

#130 Fix application crash involving request timeouts
  src/services/geocode.js
Labels: bug
